#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgres-setup
#data:
#  create.sql: |
#    docker run --name some-postgres -e POSTGRES_PASSWORD=fv2122db -d postgres
#---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: fv2122db
  database: fitervari
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitervari-database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: fitervari-database
      containers:
        - name: postgres
          image: postgres:alpine
          resources:
            #limits:
            #  memory: "1Gi"
            #  cpu: "1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: username
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: password
            #- name: POSTGRES_ROOT_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: postgres-admin
            #      key: password
            #- name: POSTGRES_ROOT_HOST
            #  value: '%'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    component: postgres
