apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitervari-keycloak-deployment
  namespace: student-m-rausch-schott
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitervari-keycloak
  template:
    metadata:
      labels:
        app: fitervari-keycloak
    spec:
      containers:
        - name: fitervari-keycloak
          image: bitnami/keycloak:latest
          env:
          - name: KEYCLOAK_DATABASE_HOST
            value: "postgres"
          - name: KEYCLOAK_DATABASE_USER
            value: "postgres"
          - name: KEYCLOAK_DATABASE_PASSWORD
            value: "fv2122db"
          - name: KEYCLOAK_DATABASE_NAME
            value: "fitervarikeycloak"
      imagePullSecrets:
        - name: registry-auth-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: fitervari-keycloak-service
  namespace: student-m-rausch-schott
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: fitervari-keycloak
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitervari-keycloak-ingress
  namespace: student-m-rausch-schott
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /m.rausch-schott/fitervari/keycloak(.*)$
            pathType: Prefix
            backend:
              service:
                name: fitervari-keycloak-service
                port:
                  number: 8080

                  