//
// Exercise.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Exercise: Codable, Hashable {

    public var id: String?
    public var sets: Int?
    public var repetitions: Int?
    public var description: String?

    public init(id: String? = nil, sets: Int? = nil, repetitions: Int? = nil, description: String? = nil) {
        self.id = id
        self.sets = sets
        self.repetitions = repetitions
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case sets
        case repetitions
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(sets, forKey: .sets)
        try container.encodeIfPresent(repetitions, forKey: .repetitions)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

