//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, Hashable {

    public var id: Int64
    public var firstname: String
    public var lastname: String
    public var trainer: Int64
    public var creationDate: Int64

    public init(id: Int64, firstname: String, lastname: String, trainer: Int64, creationDate: Int64) {
        self.id = id
        self.firstname = firstname
        self.lastname = lastname
        self.trainer = trainer
        self.creationDate = creationDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case firstname
        case lastname
        case trainer
        case creationDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(firstname, forKey: .firstname)
        try container.encode(lastname, forKey: .lastname)
        try container.encode(trainer, forKey: .trainer)
        try container.encode(creationDate, forKey: .creationDate)
    }
}

