//
// WorkoutSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkoutSession: Codable, Hashable {

    public var id: String?
    public var plan: Int?
    public var date: String?
    public var healthData: [HealthData]?

    public init(id: String? = nil, plan: Int? = nil, date: String? = nil, healthData: [HealthData]? = nil) {
        self.id = id
        self.plan = plan
        self.date = date
        self.healthData = healthData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case plan
        case date
        case healthData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(healthData, forKey: .healthData)
    }
}

